---
- hosts: pxe
  become: yes

  tasks:
    - name: Ensure dnsmasq, syslinux, tftp-server, vsftpd and firewalld are installed.
      yum:
        name:
          - dnsmasq
          - syslinux
          - tftp-server
          - vsftpd
          - firewalld
        state: present

    - name: Ensure pxelinux.cfg directory exists.
      file:
        path: /var/lib/tftpboot/pxelinux.cfg
        state: directory
        mode: '0755'

    - name: Ensure vsftpd pub directory exists.
      file:
        path: /var/ftp/pub
        state: directory
        mode: '0755'
        owner: nobody
        group: nobody
        recurse: yes

    - name: copy files into the boot locations
      copy:
        src: /usr/share/syslinux/
        dest: /var/lib/tftpboot
        mode: '0755'
        remote_src: yes

    - name: import the config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0755"
      with_items: 
        - src: default
          dest: /var/lib/tftpboot/pxelinux.cfg/default
        - src: dnsmasq.conf
          dest: /etc/dnsmasq.conf
        - src: vsftpd.conf
          dest: /etc/vsftpd/vsftpd.conf
        

    - name: Ensure all the daemons are running.
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - dnsmasq
        - vsftpd
        - firewalld

    - name: Configure allowed services with firewalld.
      firewalld:
        state: "{{ item.state }}"
        service: "{{ item.service }}"
        zone: public
        immediate: yes
        permanent: yes
      with_items:
        #ssh
        - { state: 'enabled', service: 'ssh' }
        #ftp
        - { state: 'enabled', service: 'ftp' }
        #dns
        - { state: 'enabled', service: 'dns' }
        #dns
        - { state: 'enabled', service: 'dhcp' }

    - name: Open tftp port.
      firewalld:
        state: 'enabled'
        port: "{{ item }}"
        zone: public
        immediate: yes
        permanent: yes
      with_items:
        - '69/udp'
        - '4011/udp'
        - '4000-5000/tcp'

    - name: Restart firewalld and dnsmasq.
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - firewalld
        - dnsmasq