---
- hosts: all
  become: yes

  #playbooks:
  #  - distros.yml

  vars_files:
    - vars.yml

  tasks:
    - name: Ensure vsftpd and firewalld are installed.
      yum:
        name:
          - vsftpd
          - firewalld
        state: present

    - name: Ensure pub directory exists.
      file:
        path: /var/ftp/pub
        state: directory
        mode: '0755'
        owner: nobody
        group: nobody
        recurse: yes

    - name: import the config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0755"
      with_items: 
        - src: vsftpd.conf
          dest: /etc/vsftpd/vsftpd.conf

    - name: Ensure all the daemons are running.
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - vsftpd
        - firewalld

    - name: Configure allowed services with firewalld.
      firewalld:
        state: "{{ item.state }}"
        service: "{{ item.service }}"
        zone: public
        immediate: yes
        permanent: yes
      with_items:
        #ssh
        - { state: 'enabled', service: 'ssh' }
        #ftp
        - { state: 'enabled', service: 'ftp' }
        #dns
        - { state: 'enabled', service: 'dns' }
        #dns
        - { state: 'enabled', service: 'dhcp' }

    - name: Open tftp port.
      firewalld:
        state: 'enabled'
        port: "{{ item }}"
        zone: public
        immediate: yes
        permanent: yes
      with_items:
        - '69/udp'
        - '4011/udp'
        - '4000-5000/tcp'

    - name: Restart firewalld and vsftpd.
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - firewalld
        - vsftpd