---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Ensure dnsmasq, syslinux, tftp-server and firewalld are installed.
      yum:
        name:
          - dnsmasq
          - syslinux
          - tftp-server
          - firewalld
        state: present

    - name: Ensure pxelinux.cfg and distro directories exist.
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /var/lib/tftpboot/pxelinux.cfg
        - "/var/lib/tftpboot/{{ tftp_dir }}"

    - name: Ensure OS files exist.
      get_url:
        url: "{{ linux_url }}"
        dest: "{{ download_dir }}/linux-{{ linux_ver }}.iso"
        #checksum: "{{ linux_checksum }}"

    - name: mount the OS iso
      mount:
        path: /mnt
        src: "{{ download_dir }}/linux-{{ linux_ver }}.iso"
        fstype: iso9660
        opts: ro,noauto
        state: mounted

    - name: copy files into the boot locations
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0755'
        remote_src: yes
      with_items:
        - src: /usr/share/syslinux/
          dest: /var/lib/tftpboot
        - src: /mnt/images/pxeboot/vmlinuz
          dest: "/var/lib/tftpboot/{{ tftp_dir }}"
        - src: /mnt/images/pxeboot/initrd.img
          dest: "/var/lib/tftpboot/{{ tftp_dir }}"

    - name: import the config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0755"
        backup: yes
      with_items: 
        - src: default
          dest: /var/lib/tftpboot/pxelinux.cfg/default
        - src: dnsmasq.conf
          dest: /etc/dnsmasq.conf

#    - name: unmount OS ISOs
#      mount:
#        path: /mnt
#        state: unmounted

    - name: Ensure all the daemons are running.
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - dnsmasq
        - firewalld

    - name: Configure allowed services with firewalld.
      firewalld:
        state: "{{ item.state }}"
        service: "{{ item.service }}"
        zone: public
        immediate: yes
        permanent: yes
      with_items:
        #ssh
        - { state: 'enabled', service: 'ssh' }
        #ftp
        - { state: 'enabled', service: 'ftp' }
        #dns
        - { state: 'enabled', service: 'dns' }
        #dns
        - { state: 'enabled', service: 'dhcp' }

    - name: Open tftp port.
      firewalld:
        state: 'enabled'
        port: "{{ item }}"
        zone: public
        immediate: yes
        permanent: yes
      with_items:
        - '69/udp'
        - '4011/udp'
        - '4000-5000/tcp'

    - name: Restart firewalld and dnsmasq.
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - firewalld
        - dnsmasq